-- Tabela para armazenar as refeições da dieta personalizada com macros
create table if not exists ayra_dieta_refeicoes (
  id bigint generated by default as identity primary key,
  id_usuario uuid references auth.users not null,
  tipo_refeicao text not null, -- 'Café da manhã', 'Almoço', etc.
  horario time not null,
  descricao text not null,
  calorias numeric,
  proteina numeric, -- gramas
  carboidratos numeric, -- gramas
  gorduras numeric, -- gramas
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Garante que o usuário só tenha uma refeição de cada tipo (opcional, dependendo da regra de negócio. 
  -- Se puder ter várias opções de café da manhã, remova esta constraint)
  unique(id_usuario, tipo_refeicao)
);

-- Políticas de segurança (RLS)
alter table ayra_dieta_refeicoes enable row level security;

create policy "Usuários podem ver suas próprias refeições de dieta"
  on ayra_dieta_refeicoes for select
  using (auth.uid() = id_usuario);

create policy "Usuários podem inserir suas próprias refeições de dieta"
  on ayra_dieta_refeicoes for insert
  with check (auth.uid() = id_usuario);

create policy "Usuários podem atualizar suas próprias refeições de dieta"
  on ayra_dieta_refeicoes for update
  using (auth.uid() = id_usuario);

create policy "Usuários podem deletar suas próprias refeições de dieta"
  on ayra_dieta_refeicoes for delete
  using (auth.uid() = id_usuario);
