-- Create ayra_metas table
CREATE TABLE IF NOT EXISTS ayra_metas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    data_inicio DATE DEFAULT CURRENT_DATE,
    -- Metas nutricionais
    calorias_diarias INT NOT NULL,
    proteina_g INT NOT NULL,
    carboidrato_g INT NOT NULL,
    gordura_g INT NOT NULL,
    -- Metas de estilo de vida
    agua_ml INT,
    dias_exercicio_semana INT,
    horas_sono INT,
    -- Metas de acompanhamento
    peso_corporal_kg DECIMAL(5,2),
    meta_consistencia_dias INT DEFAULT 5,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create ayra_diario_header table
CREATE TABLE IF NOT EXISTS ayra_diario_header (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    data_consumo DATE DEFAULT CURRENT_DATE,
    calorias_total_dia INT DEFAULT 0,
    observacoes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(id_usuario, data_consumo)
);

-- Create ayra_diario_detalhes table
CREATE TABLE IF NOT EXISTS ayra_diario_detalhes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_diario_header BIGINT REFERENCES ayra_diario_header(id) ON DELETE CASCADE,
    horario_refeicao TIME NOT NULL,
    tipo_refeicao VARCHAR(50) NOT NULL, -- 'Café', 'Almoço', 'Jantar', 'Lanche'
    alimento_descricao TEXT NOT NULL,
    macros_estimados_json JSONB DEFAULT '{}'::jsonb,
    flag_restricao BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create ayra_diario_lifestyle table for daily lifestyle tracking
CREATE TABLE IF NOT EXISTS ayra_diario_lifestyle (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    data_registro DATE DEFAULT CURRENT_DATE,
    -- Lifestyle metrics
    agua_ml INT DEFAULT 0,
    exercicio_feito BOOLEAN DEFAULT FALSE,
    horas_sono DECIMAL(3,1),
    humor VARCHAR(20), -- 'great', 'good', 'ok', 'bad'
    peso_kg DECIMAL(5,2),
    -- Notes
    observacoes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(id_usuario, data_registro)
);

-- Create a mock ayra_cadastro table if it doesn't exist (for reference/testing)
-- In production, this should already exist as per requirements
CREATE TABLE IF NOT EXISTS ayra_cadastro (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario UUID REFERENCES auth.users(id) ON DELETE CASCADE UNIQUE,
    nome TEXT,
    telefone TEXT,
    idade TEXT,
    problemas_de_saude TEXT,
    restricoes TEXT, -- e.g., 'alergia a amendoim'
    cadastro_completo VARCHAR(10) DEFAULT 'NAO', -- 'SIM' or 'NAO'
    objetivo TEXT, -- e.g., 'ganhar massa muscular'
    dificuldade TEXT, -- e.g., 'rotina corrida'
    tem_nutri_ou_dieta TEXT, -- e.g., 'sigo uma dieta mas sem acompanhamento'
    peso_altura TEXT, -- e.g., '90kg, 1,73m'
    info_extra TEXT,
    plano VARCHAR(20) DEFAULT 'free', -- 'free' or 'premium'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS Policies (Row Level Security) - Basic Setup
ALTER TABLE ayra_metas ENABLE ROW LEVEL SECURITY;
ALTER TABLE ayra_diario_header ENABLE ROW LEVEL SECURITY;
ALTER TABLE ayra_diario_detalhes ENABLE ROW LEVEL SECURITY;
ALTER TABLE ayra_cadastro ENABLE ROW LEVEL SECURITY;

-- Policy: Users can only see/edit their own data
CREATE POLICY "Users can view their own metas" ON ayra_metas FOR SELECT USING (auth.uid() = id_usuario);
CREATE POLICY "Users can insert their own metas" ON ayra_metas FOR INSERT WITH CHECK (auth.uid() = id_usuario);
CREATE POLICY "Users can update their own metas" ON ayra_metas FOR UPDATE USING (auth.uid() = id_usuario);

CREATE POLICY "Users can view their own diario header" ON ayra_diario_header FOR SELECT USING (auth.uid() = id_usuario);
CREATE POLICY "Users can insert their own diario header" ON ayra_diario_header FOR INSERT WITH CHECK (auth.uid() = id_usuario);
CREATE POLICY "Users can update their own diario header" ON ayra_diario_header FOR UPDATE USING (auth.uid() = id_usuario);

CREATE POLICY "Users can view their own diario detalhes" ON ayra_diario_detalhes FOR SELECT USING (
    EXISTS (SELECT 1 FROM ayra_diario_header WHERE id = ayra_diario_detalhes.id_diario_header AND id_usuario = auth.uid())
);
CREATE POLICY "Users can insert their own diario detalhes" ON ayra_diario_detalhes FOR INSERT WITH CHECK (
    EXISTS (SELECT 1 FROM ayra_diario_header WHERE id = ayra_diario_detalhes.id_diario_header AND id_usuario = auth.uid())
);

CREATE POLICY "Users can view their own cadastro" ON ayra_cadastro FOR SELECT USING (auth.uid() = id_usuario);
CREATE POLICY "Users can update their own cadastro" ON ayra_cadastro FOR UPDATE USING (auth.uid() = id_usuario);

-- ============================================
-- BIBLIOTECA DE ALIMENTOS - TABELA TACO
-- ============================================

-- Tabela principal com dados da Tabela TACO (Tabela Brasileira de Composição de Alimentos - UNICAMP)
CREATE TABLE IF NOT EXISTS tabela_taco (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_taco VARCHAR(10) UNIQUE, -- Código oficial da TACO
    nome_alimento TEXT NOT NULL,
    categoria VARCHAR(100), -- 'Cereais', 'Leguminosas', 'Carnes', 'Laticínios', etc.
    
    -- Valores nutricionais por 100g
    energia_kcal DECIMAL(7,2), -- Calorias
    proteina_g DECIMAL(6,2),
    lipideos_g DECIMAL(6,2), -- Gorduras totais
    carboidrato_g DECIMAL(6,2),
    fibra_g DECIMAL(6,2),
    
    -- Micronutrientes (opcional, pode expandir)
    calcio_mg DECIMAL(7,2),
    ferro_mg DECIMAL(6,2),
    sodio_mg DECIMAL(7,2),
    
    -- Metadados
    porcao_padrao_g DECIMAL(6,2) DEFAULT 100, -- Porção padrão em gramas
    unidade_caseira VARCHAR(50), -- 'colher de sopa', 'xícara', 'unidade', etc.
    peso_unidade_caseira_g DECIMAL(6,2), -- Peso da unidade caseira em gramas
    
    -- Busca e organização
    palavras_chave TEXT[], -- Array para facilitar busca: ['arroz', 'integral', 'cozido']
    popular BOOLEAN DEFAULT FALSE, -- Alimentos mais comuns
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Índices para busca rápida
CREATE INDEX IF NOT EXISTS idx_tabela_taco_nome ON tabela_taco USING gin(to_tsvector('portuguese', nome_alimento));
CREATE INDEX IF NOT EXISTS idx_tabela_taco_categoria ON tabela_taco(categoria);
CREATE INDEX IF NOT EXISTS idx_tabela_taco_popular ON tabela_taco(popular) WHERE popular = TRUE;
CREATE INDEX IF NOT EXISTS idx_tabela_taco_palavras_chave ON tabela_taco USING gin(palavras_chave);

-- Tabela de favoritos do usuário
CREATE TABLE IF NOT EXISTS ayra_alimentos_favoritos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    id_alimento BIGINT REFERENCES tabela_taco(id) ON DELETE CASCADE,
    apelido TEXT, -- Nome personalizado pelo usuário (ex: "Meu frango grelhado")
    porcao_favorita_g DECIMAL(6,2), -- Porção que o usuário costuma consumir
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(id_usuario, id_alimento)
);

-- Tabela de templates de refeições (refeições salvas para reutilizar)
CREATE TABLE IF NOT EXISTS ayra_templates_refeicao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    nome_template VARCHAR(100) NOT NULL, -- 'Meu café da manhã padrão'
    tipo_refeicao VARCHAR(50), -- 'Café', 'Almoço', 'Jantar', etc.
    descricao TEXT,
    itens_json JSONB NOT NULL, -- Array de alimentos com quantidades
    -- Exemplo: [{"id_alimento": 123, "quantidade_g": 150, "nome": "Arroz integral"}]
    
    -- Totais calculados
    total_calorias DECIMAL(7,2),
    total_proteina_g DECIMAL(6,2),
    total_carboidrato_g DECIMAL(6,2),
    total_gordura_g DECIMAL(6,2),
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS Policies para as novas tabelas
ALTER TABLE tabela_taco ENABLE ROW LEVEL SECURITY;
ALTER TABLE ayra_alimentos_favoritos ENABLE ROW LEVEL SECURITY;
ALTER TABLE ayra_templates_refeicao ENABLE ROW LEVEL SECURITY;

-- Tabela TACO é pública (todos podem ler)
CREATE POLICY "Anyone can view TACO table" ON tabela_taco FOR SELECT USING (true);

-- Favoritos: usuários só veem seus próprios
CREATE POLICY "Users can view their own favorites" ON ayra_alimentos_favoritos FOR SELECT USING (auth.uid() = id_usuario);
CREATE POLICY "Users can insert their own favorites" ON ayra_alimentos_favoritos FOR INSERT WITH CHECK (auth.uid() = id_usuario);
CREATE POLICY "Users can delete their own favorites" ON ayra_alimentos_favoritos FOR DELETE USING (auth.uid() = id_usuario);
CREATE POLICY "Users can update their own favorites" ON ayra_alimentos_favoritos FOR UPDATE USING (auth.uid() = id_usuario);

-- Templates: usuários só veem seus próprios
CREATE POLICY "Users can view their own templates" ON ayra_templates_refeicao FOR SELECT USING (auth.uid() = id_usuario);
CREATE POLICY "Users can insert their own templates" ON ayra_templates_refeicao FOR INSERT WITH CHECK (auth.uid() = id_usuario);
CREATE POLICY "Users can update their own templates" ON ayra_templates_refeicao FOR UPDATE USING (auth.uid() = id_usuario);
CREATE POLICY "Users can delete their own templates" ON ayra_templates_refeicao FOR DELETE USING (auth.uid() = id_usuario);

-- ============================================
-- DADOS INICIAIS - ALIMENTOS POPULARES DA TACO
-- ============================================

-- Inserir alguns alimentos populares da Tabela TACO (versão simplificada)
-- Em produção, você importaria o CSV completo da TACO

INSERT INTO tabela_taco (codigo_taco, nome_alimento, categoria, energia_kcal, proteina_g, lipideos_g, carboidrato_g, fibra_g, porcao_padrao_g, unidade_caseira, peso_unidade_caseira_g, palavras_chave, popular) VALUES
-- Cereais
('C001', 'Arroz branco cozido', 'Cereais', 128, 2.5, 0.2, 28.1, 1.6, 100, 'colher de sopa', 25, ARRAY['arroz', 'branco', 'cozido'], true),
('C002', 'Arroz integral cozido', 'Cereais', 124, 2.6, 1.0, 25.8, 2.7, 100, 'colher de sopa', 25, ARRAY['arroz', 'integral', 'cozido'], true),
('C003', 'Macarrão cozido', 'Cereais', 135, 4.5, 0.6, 28.4, 1.4, 100, 'colher de sopa', 30, ARRAY['macarrão', 'massa', 'cozido'], true),
('C004', 'Pão francês', 'Cereais', 300, 8.0, 3.1, 58.6, 2.3, 50, 'unidade', 50, ARRAY['pão', 'francês'], true),
('C005', 'Aveia em flocos', 'Cereais', 394, 13.9, 8.5, 66.6, 9.1, 30, 'colher de sopa', 15, ARRAY['aveia', 'flocos'], true),

-- Carnes
('M001', 'Frango grelhado (peito)', 'Carnes', 165, 31.0, 3.6, 0, 0, 100, 'filé médio', 120, ARRAY['frango', 'peito', 'grelhado'], true),
('M002', 'Carne bovina magra grelhada', 'Carnes', 219, 26.0, 12.0, 0, 0, 100, 'bife médio', 100, ARRAY['carne', 'bovina', 'bife', 'grelhado'], true),
('M003', 'Ovo cozido', 'Carnes', 155, 13.0, 11.0, 1.1, 0, 50, 'unidade', 50, ARRAY['ovo', 'cozido'], true),
('M004', 'Peixe grelhado (tilápia)', 'Carnes', 96, 20.0, 1.7, 0, 0, 100, 'filé médio', 120, ARRAY['peixe', 'tilápia', 'grelhado'], true),

-- Laticínios
('L001', 'Leite integral', 'Laticínios', 61, 3.2, 3.5, 4.6, 0, 200, 'copo', 200, ARRAY['leite', 'integral'], true),
('L002', 'Iogurte natural', 'Laticínios', 51, 4.1, 1.5, 6.0, 0, 150, 'pote', 150, ARRAY['iogurte', 'natural'], true),
('L003', 'Queijo minas frescal', 'Laticínios', 264, 17.4, 20.8, 3.8, 0, 30, 'fatia', 30, ARRAY['queijo', 'minas', 'frescal'], true),

-- Leguminosas
('LG001', 'Feijão preto cozido', 'Leguminosas', 77, 4.5, 0.5, 14.0, 4.5, 100, 'concha', 80, ARRAY['feijão', 'preto', 'cozido'], true),
('LG002', 'Feijão carioca cozido', 'Leguminosas', 76, 4.8, 0.5, 13.6, 8.5, 100, 'concha', 80, ARRAY['feijão', 'carioca', 'cozido'], true),
('LG003', 'Lentilha cozida', 'Leguminosas', 93, 6.3, 0.4, 16.3, 5.1, 100, 'colher de sopa', 30, ARRAY['lentilha', 'cozida'], true),

-- Vegetais
('V001', 'Alface', 'Vegetais', 15, 1.4, 0.2, 2.2, 2.0, 50, 'folhas', 50, ARRAY['alface', 'salada'], true),
('V002', 'Tomate', 'Vegetais', 15, 1.1, 0.2, 3.1, 1.2, 80, 'unidade média', 80, ARRAY['tomate'], true),
('V003', 'Brócolis cozido', 'Vegetais', 25, 3.4, 0.4, 4.0, 3.4, 100, 'ramo', 100, ARRAY['brócolis', 'cozido'], true),
('V004', 'Batata doce cozida', 'Vegetais', 77, 0.6, 0.1, 18.4, 2.2, 100, 'unidade média', 100, ARRAY['batata', 'doce', 'cozida'], true),

-- Frutas
('F001', 'Banana', 'Frutas', 98, 1.3, 0.1, 26.0, 2.0, 100, 'unidade média', 100, ARRAY['banana'], true),
('F002', 'Maçã', 'Frutas', 56, 0.3, 0.1, 15.0, 1.3, 130, 'unidade média', 130, ARRAY['maçã'], true),
('F003', 'Laranja', 'Frutas', 45, 1.0, 0.1, 11.5, 2.2, 180, 'unidade média', 180, ARRAY['laranja'], true),
('F004', 'Abacate', 'Frutas', 96, 1.2, 8.4, 6.4, 3.3, 100, 'metade', 100, ARRAY['abacate'], true),

-- Gorduras e Óleos
('G001', 'Azeite de oliva', 'Gorduras', 884, 0, 100, 0, 0, 10, 'colher de sopa', 10, ARRAY['azeite', 'oliva'], true),
('G002', 'Manteiga', 'Gorduras', 717, 0.6, 81.0, 0.1, 0, 10, 'colher de chá', 5, ARRAY['manteiga'], true),

-- Oleaginosas
('O001', 'Amendoim', 'Oleaginosas', 544, 27.2, 43.9, 20.3, 8.0, 30, 'punhado', 30, ARRAY['amendoim'], true),
('O002', 'Castanha de caju', 'Oleaginosas', 570, 18.5, 46.3, 28.7, 3.7, 30, 'punhado', 30, ARRAY['castanha', 'caju'], true)

ON CONFLICT (codigo_taco) DO NOTHING;
