-- ============================================
-- SCHEMA SIMPLIFICADO - AYRA MVP
-- ============================================
-- Mantém apenas o essencial no banco de dados:
-- 1. Autenticação e perfil básico
-- 2. Pontuação para ranking
-- 3. Histórico de chat (memória da IA)
-- ============================================

-- ============================================
-- 1. TABELA DE USUÁRIOS (Perfil + Plano)
-- ============================================
CREATE TABLE IF NOT EXISTS public.ayra_users (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    
    -- Dados básicos
    nome TEXT NOT NULL,
    email TEXT,
    telefone TEXT,
    
    -- Plano
    plano VARCHAR(20) DEFAULT 'free', -- 'free' ou 'premium'
    
    -- Gamificação
    pontuacao INTEGER DEFAULT 0,
    nivel INTEGER DEFAULT 1,
    
    -- Auditoria
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Índices
CREATE INDEX IF NOT EXISTS idx_ayra_users_pontuacao ON public.ayra_users(pontuacao DESC);
CREATE INDEX IF NOT EXISTS idx_ayra_users_plano ON public.ayra_users(plano);

-- RLS (Row Level Security)
ALTER TABLE public.ayra_users ENABLE ROW LEVEL SECURITY;

-- Políticas RLS
CREATE POLICY "Users can view their own profile"
ON public.ayra_users FOR SELECT
USING (auth.uid() = id);

CREATE POLICY "Users can update their own profile"
ON public.ayra_users FOR UPDATE
USING (auth.uid() = id);

CREATE POLICY "Users can insert their own profile"
ON public.ayra_users FOR INSERT
WITH CHECK (auth.uid() = id);

-- Política para visualizar ranking (todos podem ver pontuação de todos)
CREATE POLICY "Anyone can view ranking"
ON public.ayra_users FOR SELECT
USING (true);

-- ============================================
-- 2. HISTÓRICO DE CHAT (Memória da IA)
-- ============================================
CREATE TABLE IF NOT EXISTS public.ayra_chat_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.ayra_users(id) ON DELETE CASCADE NOT NULL,
    
    -- Mensagem
    role VARCHAR(20) NOT NULL, -- 'user' ou 'assistant'
    content TEXT NOT NULL,
    
    -- Contexto (opcional - para melhorar respostas da IA)
    context JSONB, -- Pode incluir: peso atual, objetivo, restrições, etc.
    
    -- Timestamp
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Índices
CREATE INDEX IF NOT EXISTS idx_ayra_chat_user_id ON public.ayra_chat_history(user_id);
CREATE INDEX IF NOT EXISTS idx_ayra_chat_created_at ON public.ayra_chat_history(created_at DESC);

-- RLS
ALTER TABLE public.ayra_chat_history ENABLE ROW LEVEL SECURITY;

-- Políticas RLS
CREATE POLICY "Users can view their own chat history"
ON public.ayra_chat_history FOR SELECT
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own messages"
ON public.ayra_chat_history FOR INSERT
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own messages"
ON public.ayra_chat_history FOR DELETE
USING (auth.uid() = user_id);

-- ============================================
-- 3. RANKING GLOBAL (View Materializada)
-- ============================================
-- View para ranking otimizado
CREATE OR REPLACE VIEW public.ayra_ranking AS
SELECT 
    id,
    nome,
    pontuacao,
    nivel,
    ROW_NUMBER() OVER (ORDER BY pontuacao DESC, created_at ASC) as posicao
FROM public.ayra_users
WHERE pontuacao > 0
ORDER BY pontuacao DESC
LIMIT 100;

-- ============================================
-- 4. FUNÇÕES ÚTEIS
-- ============================================

-- Função para atualizar pontuação
CREATE OR REPLACE FUNCTION public.update_user_score(
    user_id UUID,
    points_to_add INTEGER
)
RETURNS void AS $$
BEGIN
    UPDATE public.ayra_users
    SET 
        pontuacao = pontuacao + points_to_add,
        nivel = FLOOR((pontuacao + points_to_add) / 100) + 1,
        updated_at = now()
    WHERE id = user_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Função para limpar histórico de chat antigo (> 90 dias)
CREATE OR REPLACE FUNCTION public.cleanup_old_chat_history()
RETURNS void AS $$
BEGIN
    DELETE FROM public.ayra_chat_history
    WHERE created_at < now() - INTERVAL '90 days';
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Função para obter contexto do usuário para IA
CREATE OR REPLACE FUNCTION public.get_user_context(user_id UUID)
RETURNS JSONB AS $$
DECLARE
    user_data RECORD;
    recent_messages TEXT[];
BEGIN
    -- Busca dados do usuário
    SELECT nome, plano INTO user_data
    FROM public.ayra_users
    WHERE id = user_id;
    
    -- Busca últimas 5 mensagens
    SELECT ARRAY_AGG(content ORDER BY created_at DESC)
    INTO recent_messages
    FROM (
        SELECT content
        FROM public.ayra_chat_history
        WHERE ayra_chat_history.user_id = get_user_context.user_id
        ORDER BY created_at DESC
        LIMIT 5
    ) recent;
    
    -- Retorna contexto em JSON
    RETURN jsonb_build_object(
        'nome', user_data.nome,
        'plano', user_data.plano,
        'recent_messages', recent_messages
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ============================================
-- 5. TRIGGERS
-- ============================================

-- Trigger para atualizar updated_at automaticamente
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_ayra_users_updated_at
BEFORE UPDATE ON public.ayra_users
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();

-- ============================================
-- 6. DADOS INICIAIS (Opcional)
-- ============================================

-- Você pode adicionar usuários de teste aqui se necessário

-- ============================================
-- FIM DO SCHEMA SIMPLIFICADO
-- ============================================

/*
INSTRUÇÕES DE USO:

1. Execute este script no SQL Editor do Supabase
2. Configure as variáveis de ambiente:
   - VITE_SUPABASE_URL
   - VITE_SUPABASE_ANON_KEY

3. Dados armazenados LOCALMENTE (localStorage):
   - Peso e altura
   - Registros de alimentação
   - Água, sono, exercícios
   - Metas nutricionais
   - Histórico de progresso

4. Dados armazenados no SUPABASE:
   - Autenticação (email/telefone)
   - Nome e plano do usuário
   - Pontuação para ranking
   - Histórico de chat (memória da IA)

5. Sistema de pontuação:
   - Registrar refeição: +10 pontos
   - Completar meta de água: +5 pontos
   - Fazer exercício: +15 pontos
   - Streak de 7 dias: +50 pontos
   - Nível = pontuação / 100

6. Limpeza automática:
   - Histórico de chat > 90 dias é deletado automaticamente
   - Execute: SELECT public.cleanup_old_chat_history();
*/
