-- ============================================
-- TABELAS ADMINISTRATIVAS E MÉTRICAS
-- ============================================

-- Tabela de assinaturas/pagamentos
CREATE TABLE IF NOT EXISTS ayra_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    
    -- Status da assinatura
    status VARCHAR(20) DEFAULT 'pending', -- 'active', 'canceled', 'pending', 'expired'
    
    -- Datas
    subscription_start TIMESTAMP WITH TIME ZONE,
    subscription_end TIMESTAMP WITH TIME ZONE,
    canceled_at TIMESTAMP WITH TIME ZONE,
    
    -- Financeiro
    plan_type VARCHAR(20) DEFAULT 'monthly', -- 'monthly', 'yearly'
    amount_paid DECIMAL(10,2),
    currency VARCHAR(3) DEFAULT 'BRL',
    
    -- Informações de pagamento (Stripe, etc)
    payment_provider VARCHAR(50), -- 'stripe', 'mercadopago', etc
    payment_id VARCHAR(255), -- ID do pagamento no provedor
    customer_id VARCHAR(255), -- ID do cliente no provedor
    
    -- Metadados
    auto_renew BOOLEAN DEFAULT TRUE,
    trial_used BOOLEAN DEFAULT FALSE,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    
    UNIQUE(id_usuario, subscription_start)
);

-- Tabela de eventos de conversão (free -> premium)
CREATE TABLE IF NOT EXISTS ayra_conversion_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    
    -- Dados da conversão
    converted_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    days_to_convert INT, -- Quantos dias levou desde o cadastro
    
    -- Contexto da conversão
    conversion_source VARCHAR(100), -- 'dashboard_banner', 'chat_limit', 'premium_page', etc
    subscription_value DECIMAL(10,2),
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Tabela de eventos de churn (cancelamento)
CREATE TABLE IF NOT EXISTS ayra_churn_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    id_subscription BIGINT REFERENCES ayra_subscriptions(id) ON DELETE CASCADE,
    
    -- Dados do churn
    churned_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    subscription_duration_days INT, -- Quantos dias ficou como premium
    total_revenue DECIMAL(10,2), -- Total pago durante a assinatura
    
    -- Motivo do cancelamento
    churn_reason VARCHAR(50), -- 'price', 'not_using', 'found_alternative', 'other'
    churn_feedback TEXT,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Tabela de atividade de usuários (para calcular engajamento)
CREATE TABLE IF NOT EXISTS ayra_user_activity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    
    -- Atividade
    activity_date DATE DEFAULT CURRENT_DATE,
    login_count INT DEFAULT 0,
    messages_sent INT DEFAULT 0,
    meals_logged INT DEFAULT 0,
    
    -- Engajamento
    session_duration_minutes INT DEFAULT 0,
    features_used TEXT[], -- Array de features usadas: ['chat', 'diary', 'progress']
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    
    UNIQUE(id_usuario, activity_date)
);

-- Tabela de receita diária (para facilitar relatórios)
CREATE TABLE IF NOT EXISTS ayra_daily_revenue (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    revenue_date DATE DEFAULT CURRENT_DATE,
    
    -- Métricas do dia
    total_revenue DECIMAL(10,2) DEFAULT 0,
    new_subscriptions INT DEFAULT 0,
    canceled_subscriptions INT DEFAULT 0,
    active_subscriptions INT DEFAULT 0,
    
    -- MRR (Monthly Recurring Revenue)
    mrr DECIMAL(10,2) DEFAULT 0,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    
    UNIQUE(revenue_date)
);

-- Índices para performance
CREATE INDEX IF NOT EXISTS idx_subscriptions_user ON ayra_subscriptions(id_usuario);
CREATE INDEX IF NOT EXISTS idx_subscriptions_status ON ayra_subscriptions(status);
CREATE INDEX IF NOT EXISTS idx_subscriptions_dates ON ayra_subscriptions(subscription_start, subscription_end);

CREATE INDEX IF NOT EXISTS idx_conversion_user ON ayra_conversion_events(id_usuario);
CREATE INDEX IF NOT EXISTS idx_conversion_date ON ayra_conversion_events(converted_at);

CREATE INDEX IF NOT EXISTS idx_churn_user ON ayra_churn_events(id_usuario);
CREATE INDEX IF NOT EXISTS idx_churn_date ON ayra_churn_events(churned_at);

CREATE INDEX IF NOT EXISTS idx_activity_user ON ayra_user_activity(id_usuario);
CREATE INDEX IF NOT EXISTS idx_activity_date ON ayra_user_activity(activity_date);

CREATE INDEX IF NOT EXISTS idx_revenue_date ON ayra_daily_revenue(revenue_date);

-- RLS Policies
ALTER TABLE ayra_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE ayra_conversion_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE ayra_churn_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE ayra_user_activity ENABLE ROW LEVEL SECURITY;
ALTER TABLE ayra_daily_revenue ENABLE ROW LEVEL SECURITY;

-- Usuários podem ver apenas suas próprias assinaturas
CREATE POLICY "Users can view their own subscriptions" ON ayra_subscriptions FOR SELECT USING (auth.uid() = id_usuario);
CREATE POLICY "Users can view their own activity" ON ayra_user_activity FOR SELECT USING (auth.uid() = id_usuario);

-- Apenas admins podem ver eventos de conversão, churn e receita
-- Nota: Você precisará criar uma função para verificar se o usuário é admin
-- Por enquanto, vamos bloquear o acesso público
CREATE POLICY "Only admins can view conversion events" ON ayra_conversion_events FOR SELECT USING (false);
CREATE POLICY "Only admins can view churn events" ON ayra_churn_events FOR SELECT USING (false);
CREATE POLICY "Only admins can view revenue data" ON ayra_daily_revenue FOR SELECT USING (false);

-- ============================================
-- FUNÇÕES AUXILIARES PARA MÉTRICAS
-- ============================================

-- Função para calcular o tempo médio de conversão
CREATE OR REPLACE FUNCTION calculate_avg_conversion_time()
RETURNS DECIMAL AS $$
BEGIN
    RETURN (
        SELECT COALESCE(AVG(days_to_convert), 0)
        FROM ayra_conversion_events
        WHERE converted_at >= NOW() - INTERVAL '90 days'
    );
END;
$$ LANGUAGE plpgsql;

-- Função para calcular a taxa de conversão
CREATE OR REPLACE FUNCTION calculate_conversion_rate()
RETURNS DECIMAL AS $$
DECLARE
    total_users INT;
    converted_users INT;
BEGIN
    SELECT COUNT(*) INTO total_users FROM ayra_cadastro WHERE created_at >= NOW() - INTERVAL '90 days';
    SELECT COUNT(*) INTO converted_users FROM ayra_conversion_events WHERE converted_at >= NOW() - INTERVAL '90 days';
    
    IF total_users = 0 THEN
        RETURN 0;
    END IF;
    
    RETURN (converted_users::DECIMAL / total_users::DECIMAL) * 100;
END;
$$ LANGUAGE plpgsql;

-- Função para calcular churn rate mensal
CREATE OR REPLACE FUNCTION calculate_monthly_churn_rate()
RETURNS DECIMAL AS $$
DECLARE
    active_start INT;
    churned_count INT;
BEGIN
    -- Usuários ativos no início do mês
    SELECT COUNT(*) INTO active_start 
    FROM ayra_subscriptions 
    WHERE status = 'active' 
    AND subscription_start <= DATE_TRUNC('month', NOW());
    
    -- Usuários que cancelaram este mês
    SELECT COUNT(*) INTO churned_count 
    FROM ayra_churn_events 
    WHERE churned_at >= DATE_TRUNC('month', NOW());
    
    IF active_start = 0 THEN
        RETURN 0;
    END IF;
    
    RETURN (churned_count::DECIMAL / active_start::DECIMAL) * 100;
END;
$$ LANGUAGE plpgsql;

-- Função para calcular LTV médio
CREATE OR REPLACE FUNCTION calculate_average_ltv()
RETURNS DECIMAL AS $$
BEGIN
    RETURN (
        SELECT COALESCE(AVG(total_revenue), 0)
        FROM ayra_churn_events
        WHERE churned_at >= NOW() - INTERVAL '12 months'
    );
END;
$$ LANGUAGE plpgsql;

-- Função para calcular MRR (Monthly Recurring Revenue)
CREATE OR REPLACE FUNCTION calculate_current_mrr()
RETURNS DECIMAL AS $$
BEGIN
    RETURN (
        SELECT COALESCE(SUM(
            CASE 
                WHEN plan_type = 'monthly' THEN amount_paid
                WHEN plan_type = 'yearly' THEN amount_paid / 12
                ELSE 0
            END
        ), 0)
        FROM ayra_subscriptions
        WHERE status = 'active'
    );
END;
$$ LANGUAGE plpgsql;

-- ============================================
-- VIEW PARA FACILITAR CONSULTAS ADMIN
-- ============================================

-- View com informações completas de usuários para o admin
CREATE OR REPLACE VIEW admin_users_overview AS
SELECT 
    u.id,
    u.email,
    c.nome,
    c.plano,
    c.created_at as user_created_at,
    s.status as subscription_status,
    s.subscription_start,
    s.subscription_end,
    s.amount_paid as last_payment_amount,
    (
        SELECT SUM(amount_paid) 
        FROM ayra_subscriptions 
        WHERE id_usuario = u.id
    ) as total_paid,
    (
        SELECT MAX(activity_date) 
        FROM ayra_user_activity 
        WHERE id_usuario = u.id
    ) as last_active_date,
    (
        SELECT SUM(messages_sent) 
        FROM ayra_user_activity 
        WHERE id_usuario = u.id
    ) as total_messages_sent
FROM auth.users u
LEFT JOIN ayra_cadastro c ON c.id_usuario = u.id
LEFT JOIN LATERAL (
    SELECT * FROM ayra_subscriptions 
    WHERE id_usuario = u.id 
    ORDER BY created_at DESC 
    LIMIT 1
) s ON true
ORDER BY c.created_at DESC;
